blogger_blog:
    resource: @BloggerBlogBundle/Controller/
    type: annotation
    defaults: { _controller: BloggerBlogBundle:Page:index, commets: "true" }

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#app:
#    resource: "@AppBundle/Resources/config/routing.yml"