fos_user_extend:
    resource: "@FOSUserExtendBundle/Controller/"
    type:     annotation
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Controller/"
    type: annotation

app_bundle:
    resource: "@AppBundle/Controller/"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /fos

fos_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
