#security:
#    providers:
#        our_db_provider:
#            entity:
#                class: AppBundle\Entity\User
#
#    encoders:
#        AppBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 12
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~
#            pattern: ^/
#            http_basic: ~
#            provider: our_db_provider
#            form_login:
#                login_path: /login
#                check_path: /login_check
#
#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/contact, roles: ROLE_USER }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }