security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        # approach to load user if current system used as secondary for another legacy
        legacy_db_provider:
            entity:
                class: AppBundle:FOSUserChild
                property: username

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        main:
            pattern: ^/

            # approach to load user if current system used as secondary for another legacy
            provider: legacy_db_provider
            simple_preauth:
                authenticator: app.security.legacy_authenticator

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: /fos/login_check
                login_path: /fos/login
            anonymous:    true
            logout:
                path: fos_user_security_logout
#                target: index
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin,      role: ROLE_ADMIN }
        - { path: ^/contact,    role: ROLE_USER }
        - { path: ^/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,     role: ROLE_ADMIN }