security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        main:
            pattern: ^/
            http_basic: ~
            form_login:
                provider: fos_userbundle
#                csrf_provider: security.csrf.token_manager
                check_path: /fos/login_check
                login_path: /fos/login
            logout:       true
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/contact, roles: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }