blogger_blog_homepage:
  pattern: /
  defaults: { _controller: "BloggerBlogBundle:Page:index" }
  requirements:
    _method: GET

blogger_blog_about:
  pattern: /about
  defaults: { _controller: "BloggerBlogBundle:Page:about" }
  requirements:
    _method: GET

blogger_blog_contact:
  pattern: /contact
  defaults: { _controller: "BloggerBlogBundle:Page:contact" }
  requirements:
    _method: GET|POST

blogger_blog_show:
    pattern:  /{id}/{slug}/{comments}
    defaults: { _controller: "BloggerBlogBundle:Blog:show", comments: true }
    requirements:
        _method:  GET
        id: \d+

blogger_blog_comment_create:
    pattern: /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
      _method: POST
      blog_id: \d+

#blogger_blog_comment_new:
#    pattern: /comment-new/{blog_id}
#    defaults: { _controller: "BloggerBlogBundle:Comment:new" }
#    requirements:
#      _method: GET
#      blog_id: \d+