blogger_blog_homepage:
  path: /
  defaults: { _controller: "BloggerBlogBundle:Page:index" }
  requirements:
    methods: GET

blogger_blog_about:
  path: /about
  defaults: { _controller: "BloggerBlogBundle:Page:about" }
  requirements:
    methods: GET

blogger_blog_contact:
  path: /contact
  defaults: { _controller: "BloggerBlogBundle:Page:contact" }
  requirements:
    methods: GET|POST

blogger_blog_show:
    path:  /{id}/{slug}/{comments}
    defaults: { _controller: "BloggerBlogBundle:Blog:show", comments: true }
    requirements:
        methods:  GET
        id: \d+

blogger_blog_comment_create:
    path: /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
      methods: POST
      blog_id: \d+