services:
    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
        tags:
            - { name: twig.extension }

    blogger.blog.validators.comment_unique:
        class: Blogger\BlogBundle\Validator\Constraints\SimilarCommentConstraintValidator
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
        tags:
          - { name: "validator.constraint_validator", alias: "commentUnique" }