register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path: /register/create
    defaults: { _controller: AppBundle:Account:create }


login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path:     login_check
    defaults: { _controller: AppBundle:Security:loginCheck }
