services:
    app.user.password_resetting:
        class: AppBundle\EventListener\PasswordResettingListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    app.user.registration_init:
        class: AppBundle\EventListener\RegistrationInitListener
        arguments: [ "@router", "@security.token_storage" ]
        tags:
            - { name: kernel.event_subscriber }

    app.user.interactive_login:
        class: AppBundle\EventListener\LoginEventListener
        arguments: [ "@session", "@security.token_storage" ]
        tags:
            - { name: kernel.event_subscriber }

    # approach to load user if current system used as secondary for another legacy
    app.security.legacy_authenticator:
        class: AppBundle\Security\LegacyAuthenticator
        arguments:
            - "@session.storage.native"
        public: false