<?php

namespace AppBundle\Form;


use AppBundle\Entity\StatusWorkflowDefinition;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GroupStatusWorkflowDefinitionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'status_workflow_definition',
                'collection',
                [
                    'mapped'=> false,
                    'allow_add' => true,
                    'label' => false,
                    'allow_delete' => true,
                    'block_name' => '_status_workflow_matrix',
                    'prototype' => false,
                    'allow_extra_fields' => true,
                ]
            )
            ->add(
                'submit',
                'submit'
            )
            ->get('status_workflow_definition')
            ->addModelTransformer(
                new CallbackTransformer(
                    function ($original) {
                        return $original;
                    },
                    function ($submitted) {
                        return $submitted;
                    }
                )
            )
        ;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AppBundle\Entity\Group',
        ]);
    }

    public function getName()
    {
        return 'group_status_workflow_definitions_matrix';
    }
}